# Generated by Django 6.0.3 on 2026-04-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=100)),
                ('pphone', models.CharField(max_length=15)),
                ('pdisease', models.CharField(max_length=50)),
                ('pemail', models.EmailField(max_length=254)),
                ('doc_designation', models.CharField(default='Not Assigned', max_length=100)),
                ('presult', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
