# Generated by Django 6.0.3 on 2026-04-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('dname', models.CharField(max_length=40)),
                ('dqualification', models.CharField(max_length=40)),
                ('dspecilization', models.CharField(max_length=40)),
                ('ddesignation', models.CharField(max_length=40)),
                ('dexperience', models.IntegerField()),
                ('sal', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='doc_designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='presult',
            field=models.CharField(max_length=50),
        ),
    ]
